//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RodinaTurkey.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Abouts
    {
        public byte ID { get; set; }
        public string UserName { get; set; }
        public string Image { get; set; }
        public string CompanyName { get; set; }
        public string CompanyImage { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Video { get; set; }
    }
}
