//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RodinaTurkey.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SalesList
    {
        public short ID { get; set; }
        public string OneFiveDay { get; set; }
        public string FiveFifftenDay { get; set; }
        public string FifftenThrisDay { get; set; }
        public string ThirsdayPlus { get; set; }
    
        public virtual Tbl_Rentcar Tbl_Rentcar { get; set; }
    }
}
